// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<void> notifyAppOpened({required String appId}) =>
    RustLib.instance.api.crateApiNotifyAppOpened(appId: appId);

Future<void> notifyAppClosed({required String appId}) =>
    RustLib.instance.api.crateApiNotifyAppClosed(appId: appId);

Stream<WatchUiState> startBlackboardSimulation() =>
    RustLib.instance.api.crateApiStartBlackboardSimulation();

Stream<WatchUiState> startEventDrivenSimulation() =>
    RustLib.instance.api.crateApiStartEventDrivenSimulation();

class WatchUiState {
  final String heartRate;
  final String bloodPressure;
  final String steps;
  final String distance;
  final String barometricPressure;
  final String temperature;
  final bool waterInDevice;
  final String? latestMessage;

  const WatchUiState({
    required this.heartRate,
    required this.bloodPressure,
    required this.steps,
    required this.distance,
    required this.barometricPressure,
    required this.temperature,
    required this.waterInDevice,
    this.latestMessage,
  });

  @override
  int get hashCode =>
      heartRate.hashCode ^
      bloodPressure.hashCode ^
      steps.hashCode ^
      distance.hashCode ^
      barometricPressure.hashCode ^
      temperature.hashCode ^
      waterInDevice.hashCode ^
      latestMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WatchUiState &&
          runtimeType == other.runtimeType &&
          heartRate == other.heartRate &&
          bloodPressure == other.bloodPressure &&
          steps == other.steps &&
          distance == other.distance &&
          barometricPressure == other.barometricPressure &&
          temperature == other.temperature &&
          waterInDevice == other.waterInDevice &&
          latestMessage == other.latestMessage;
}
