import 'dart:async';
import 'sensor_repository.dart';
// Import your generated FRB file here (e.g., src/rust/api.dart or bridge_definitions.dart)
// import 'package:your_app_name/bridge_definitions.dart'; 

class BlackboardAdapter implements SensorRepository {
  // We use a broadcast controller so multiple UI widgets (Health, Weather, etc.) 
  // can listen to the stream at the same time without throwing an error.
  final _stateController = StreamController<WatchUiState>.broadcast();

  BlackboardAdapter() {
    _initSimulation();
  }

  void _initSimulation() {
    // startBlackboardSimulation is the Dart function generated by flutter_rust_bridge!
    // It returns a standard Dart Stream<BlackboardUiState>.
    startBlackboardSimulation().listen((rustState) {
      
      // Map the Rust-specific struct to our generic UI struct
      final uiState = WatchUiState(
        heartRate: rustState.heartRate,
        bloodPressure: rustState.bloodPressure,
        steps: rustState.steps,
        distance: rustState.distance,
        barometricPressure: rustState.barometricPressure,
        temperature: rustState.temperature,
        waterInDevice: rustState.waterInDevice,
        latestMessage: rustState.latestMessage,
      );

      // Push it to the UI!
      _stateController.add(uiState);
    });
  }

  @override
  Stream<WatchUiState> get watchStateStream => _stateController.stream;

  // Clean up memory if the adapter is ever destroyed
  void dispose() {
    _stateController.close();
  }
}