import 'dart:async';

abstract class SensorRepository {
  // A broadcast stream containing the full state of the watch
  Stream<WatchUiState> get watchStateStream;
}

// A standard Dart class to hold the data so the UI isn't tightly
// coupled to the specific class generated by flutter_rust_bridge.
class WatchUiState {
  final String heartRate;
  final String bloodPressure;
  final String steps;
  final String distance;
  final String barometricPressure;
  final String temperature;
  final bool waterInDevice;
  final String? latestMessage;

  WatchUiState({
    required this.heartRate,
    required this.bloodPressure,
    required this.steps,
    required this.distance,
    required this.barometricPressure,
    required this.temperature,
    required this.waterInDevice,
    this.latestMessage,
  });
}
