import 'package:flutter/material.dart';
// Note: 'rust_lib.dart' is the default name generated by FRB v2.
import 'package:iot_watch/src/rust/frb_generated.dart'; 
import 'package:iot_watch/domain/blackboard_adapter.dart';
import 'package:iot_watch/app.dart';

Future<void> main() async {
  // 1. Ensure Flutter bindings are initialized before doing async work
  WidgetsFlutterBinding.ensureInitialized();

  // 2. Initialize the flutter_rust_bridge 
  await RustLib.init();

  // 3. Instantiate your chosen architecture adapter
  // Later, you can swap this to EventDrivenAdapter() to test the other backend
  final sensorRepository = BlackboardAdapter();

  // 4. Run the app and inject the repository
  runApp(IoTWatchApp(repository: sensorRepository));
}